apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: bacterie
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'etats-bacterie'
        static_configs:
          - targets:
              - 'stable:8000'
              - 'hypertrophie:8000'
              - 'atrophie:8000'
              - 'impasse:8000'
      - job_name: 'state-manager'
        static_configs:
          - targets: ['state-manager:8000']