# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bacterie_pb2 as bacterie__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bacterie_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EtatBacterieStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Entrer = channel.unary_unary(
                '/bacterie.EtatBacterie/Entrer',
                request_serializer=bacterie__pb2.BacterieRequest.SerializeToString,
                response_deserializer=bacterie__pb2.BacterieResponse.FromString,
                _registered_method=True)


class EtatBacterieServicer:
    """Missing associated documentation comment in .proto file."""

    def Entrer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EtatBacterieServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Entrer': grpc.unary_unary_rpc_method_handler(
                    servicer.Entrer,
                    request_deserializer=bacterie__pb2.BacterieRequest.FromString,
                    response_serializer=bacterie__pb2.BacterieResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bacterie.EtatBacterie', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bacterie.EtatBacterie', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EtatBacterie:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Entrer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bacterie.EtatBacterie/Entrer',
            bacterie__pb2.BacterieRequest.SerializeToString,
            bacterie__pb2.BacterieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
